

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/oms/**
          filters:
            - RewritePath=/oms/(?<segment>.*), /oms/api/$\{segment}
